name: Setup
on:
  workflow_call:
  secrets:
    SOME_SECRET:
      required: true
  inputs:
    hello_message:
      required: true
      description: "A message to be passed in"
      type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: echo "input value passed in => ( ${{ inputs.hello_message }})"
      - run: echo "secret value passed in => ( ${{ secrets.SOME_SECRET }}), this should actually mask the actual secrete"